name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  build-Ububtu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Build
        run: for f in $(find . -name "*sln"); do dotnet build $f; done
      - name: RunTests
        run: for f in $(find . -name "*sln"); do dotnet test $f; done
      
  
  
